/**
 * Visual TOC Generator (Gemini 3 Flash)
 *
 * Analyzes document structure using Google Gemini 3 Flash's native PDF
 * understanding. Sends the ENTIRE PDF in a single request (1M token
 * context window) — no chunking or merging needed.
 */

import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand, BatchWriteCommand } from '@aws-sdk/lib-dynamodb';
import { getLogger } from '/opt/nodejs/utils/logger';
import { v4 as uuidv4 } from 'uuid';

const logger = getLogger('toc-extractor');

const s3Client = new S3Client({ region: process.env.AWS_REGION || 'us-east-1' });
const dynamoClient = new DynamoDBClient({ region: process.env.AWS_REGION || 'us-east-1' });
const docClient = DynamoDBDocumentClient.from(dynamoClient);

const BOOKS_TABLE = `stealth-aaas-${process.env.STAGE || 'dev'}-books`;
const CHAPTERS_TABLE = `stealth-aaas-${process.env.STAGE || 'dev'}-chapters`;
const TOPICS_TABLE = `stealth-aaas-${process.env.STAGE || 'dev'}-topics`;
const SUBTOPICS_TABLE = `stealth-aaas-${process.env.STAGE || 'dev'}-subtopics`;

interface AutoGeneratedTOC {
  chapters: Array<{
    chapterNumber: number;
    title: string;
    startPage: number;
    endPage: number;
    confidence: number;
    detectedOn: string;
  }>;
  topics: Array<{
    parentChapterNumber: number;
    topicNumber: string;
    title: string;
    startPage: number;
    endPage: number;
    confidence: number;
    detectedOn: string;
  }>;
  subTopics: Array<{
    parentTopicNumber: string;
    subTopicNumber: string;
    title: string;
    startPage: number;
    endPage: number;
    confidence: number;
    detectedOn: string;
  }>;
  subSubTopics: Array<{
    parentSubTopicNumber: string;
    subSubTopicNumber: string;
    title: string;
    startPage: number;
    endPage: number;
    confidence: number;
    detectedOn: string;
  }>;
  metadata: {
    analyzedPages: string;
    totalEntries: number;
    entriesWithPages: number;
    overallConfidence: number;
    warnings: string[];
  };
}

interface TocExtractionResult {
  chapters: { chapterId: string; title: string; bookId: string; order: number; pageStart: number; pageEnd: number }[];
  topics: { topicId: string; title: string; chapterId: string; order: number; pageStart: number; pageEnd: number }[];
  subtopics: { subtopicId: string; title: string; topicId: string; order: number; pageStart: number; pageEnd: number }[];
}

// ============================================
// Main Entry Point
// ============================================

/**
 * Generate TOC by visually analyzing the PDF with Gemini 3 Flash
 *
 * @param bookId - Book ID for logging
 * @param s3Bucket - S3 bucket containing the PDF
 * @param s3Key - S3 key for the PDF
 * @returns TocExtractionResult with generated TOC
 */
export async function extractToc(
  bookId: string,
  s3Bucket: string,
  s3Key: string
): Promise<TocExtractionResult> {
  logger.info(`[TOC Generator] Starting Gemini vision analysis for book ${bookId}...`);

  try {
    // Step 1: Download PDF from S3
    const getObjectCommand = new GetObjectCommand({
      Bucket: s3Bucket,
      Key: s3Key,
    });

    const response = await s3Client.send(getObjectCommand);
    const pdfBytes = await response.Body?.transformToByteArray();

    if (!pdfBytes) {
      throw new Error('Failed to download PDF from S3');
    }

    const pdfBuffer = Buffer.from(pdfBytes);
    const base64Pdf = pdfBuffer.toString('base64');
    logger.info(`[TOC Generator] PDF loaded (${(pdfBuffer.length / 1024 / 1024).toFixed(1)} MB). Sending to Gemini...`);

    // Step 2: Send entire PDF to Gemini in one shot
    const toc = await analyzeWithGemini(base64Pdf);
    logger.info(`[TOC Generator] Detected ${toc.chapters.length} chapters, ${toc.topics.length} topics`);

    // Step 3: Store in DynamoDB
    const result = await storeTocInDynamoDB(bookId, toc);

    logger.info(`[TOC Generator] TOC extraction complete`, {
      chaptersCount: result.chapters.length,
      topicsCount: result.topics.length,
      subtopicsCount: result.subtopics.length,
      confidence: toc.metadata.overallConfidence,
    });

    return result;
  } catch (error) {
    logger.error('[TOC Generator] Error:', error as Error);
    throw error;
  }
}

// ============================================
// Gemini Vision Analysis
// ============================================

/**
 * Send the full PDF to Gemini and get structured TOC JSON back
 */
async function analyzeWithGemini(base64Pdf: string): Promise<AutoGeneratedTOC> {
  const geminiApiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview-0409:generateContent?key=${process.env.GEMINI_API_KEY}`;

  const prompt = buildVisionAnalysisPrompt();

  logger.info(`[TOC Generator] Calling Gemini 3 Flash for structure analysis...`);

  const response = await fetch(geminiApiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType: 'application/pdf',
                data: base64Pdf,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      ],
      generationConfig: {
        maxOutputTokens: 8192,
        temperature: 0.1,
        responseMimeType: 'application/json',
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error(`[TOC Generator] Gemini API error: ${errorText}`);
    throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
  }

  const responseData = await response.json();
  const responseText = responseData.candidates?.[0]?.content?.parts?.[0]?.text || '';

  if (!responseText) {
    throw new Error('Gemini returned an empty response');
  }

  // Log token usage if available
  if (responseData.usageMetadata) {
    logger.info(`[TOC Generator] Gemini usage: ${responseData.usageMetadata.promptTokenCount} input, ${responseData.usageMetadata.candidatesTokenCount} output tokens`);
  }

  // Check for truncation
  const finishReason = responseData.candidates?.[0]?.finishReason || 'UNKNOWN';
  logger.info(`[TOC Generator] Finish reason: ${finishReason}`);

  if (finishReason === 'MAX_TOKENS') {
    logger.warn(`[TOC Generator] ⚠️ Response truncated! Retrying with chapters-only prompt...`);
    return retryWithSimplifiedPrompt(base64Pdf);
  }

  // Parse JSON
  try {
    const parsed = JSON.parse(responseText) as AutoGeneratedTOC;
    // Ensure required arrays exist
    parsed.subTopics = parsed.subTopics || [];
    parsed.subSubTopics = parsed.subSubTopics || [];
    parsed.metadata = parsed.metadata || { analyzedPages: 'all', totalEntries: 0, entriesWithPages: 0, overallConfidence: 85, warnings: [] };
    return parsed;
  } catch (parseError) {
    logger.error('[TOC Generator] JSON parse failed. Response:', responseText.substring(0, 1000));
    throw new Error(`Failed to parse Gemini JSON response: ${parseError}`);
  }
}

/**
 * Retry with a simplified prompt that only asks for chapters (much smaller output)
 */
async function retryWithSimplifiedPrompt(base64Pdf: string): Promise<AutoGeneratedTOC> {
  logger.info('[TOC Generator] Retrying with simplified chapters-only prompt...');

  const geminiApiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview-0409:generateContent?key=${process.env.GEMINI_API_KEY}`;

  const simplePrompt = `Analyze this PDF textbook. Return ONLY the top-level chapters/units as JSON.

Return this exact JSON structure:
{
  "chapters": [
    { "chapterNumber": 1, "title": "Chapter Title", "startPage": 1, "endPage": 15, "confidence": 90, "detectedOn": "Page 1" }
  ],
  "topics": [],
  "subTopics": [],
  "subSubTopics": [],
  "metadata": { "analyzedPages": "all", "totalEntries": 0, "entriesWithPages": 0, "overallConfidence": 85, "warnings": ["Simplified: chapters only due to output size limit"] }
}

Rules:
- Use sequential chapterNumber starting from 1
- startPage and endPage are PRINTED page numbers from the document
- Only include major divisions (chapters/units), not sub-sections`;

  const response = await fetch(geminiApiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            { inlineData: { mimeType: 'application/pdf', data: base64Pdf } },
            { text: simplePrompt },
          ],
        },
      ],
      generationConfig: {
        maxOutputTokens: 8192,
        temperature: 0.1,
        responseMimeType: 'application/json',
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Gemini retry API error: ${response.status}`);
  }

  const responseData = await response.json();
  const text = responseData.candidates?.[0]?.content?.parts?.[0]?.text || '';

  if (!text) {
    throw new Error('Gemini retry returned empty');
  }

  const parsed = JSON.parse(text) as AutoGeneratedTOC;
  parsed.subTopics = parsed.subTopics || [];
  parsed.subSubTopics = parsed.subSubTopics || [];
  return parsed;
}

/**
 * Build prompt for Gemini structure analysis
 */
function buildVisionAnalysisPrompt(): string {
  return `You are a textbook structure analyzer. Analyze the attached PDF document to generate a complete Table of Contents.

TASK: Visually read the entire document and identify its hierarchical structure.

DETECTION CRITERIA:
**LEVEL 1 - CHAPTER:** Major sections with titles like "Chapter 1", "Unit 1", "Module 1", or any numbered major division. These typically have large fonts, bold text, or page breaks before them.
**LEVEL 2 - TOPIC:** Numbered subsections like "1.1 Getting Started" within chapters.
**LEVEL 3 - SUB-TOPIC:** Deeper subsections like "1.1.1 Installation".
**LEVEL 4 - SUB-SUB-TOPIC:** Deepest subsections like "1.1.1.1 Windows Setup".

CRITICAL FORMATTING RULES:
1. ALWAYS use "chapterNumber" starting from 1. Even if the book calls them "Unit 1", "Module 1", etc., map them to sequential chapter numbers (1, 2, 3...).
2. Topic numbers MUST follow format "N.N" where N is the parent chapter number (e.g., "1.1", "1.2", "2.1").
3. Sub-topic numbers MUST follow format "N.N.N" (e.g., "1.1.1", "2.3.4").
4. Every entry MUST have both startPage and endPage. If a section starts and ends on the same page, use the same number for both.
5. Page numbers should be the PRINTED page numbers visible in the document, NOT the PDF viewer page count.
6. If the document has a printed "Table of Contents" section, use it as a primary reference and verify against actual content.
7. Do NOT include prefaces, forewords, acknowledgements, or appendices as chapters.
8. Return empty arrays if no entries are found for a level.

OUTPUT FORMAT:
Return ONLY valid JSON (no markdown code fences, no explanations before or after):
{
  "chapters": [
    { "chapterNumber": 1, "title": "Introduction to Economics", "startPage": 1, "endPage": 15, "confidence": 95, "detectedOn": "Page 1" }
  ],
  "topics": [
    { "parentChapterNumber": 1, "topicNumber": "1.1", "title": "Meaning of Economics", "startPage": 1, "endPage": 5, "confidence": 90, "detectedOn": "Page 1" }
  ],
  "subTopics": [
    { "parentTopicNumber": "1.1", "subTopicNumber": "1.1.1", "title": "Definition", "startPage": 1, "endPage": 3, "confidence": 85, "detectedOn": "Page 1" }
  ],
  "subSubTopics": [],
  "metadata": {
    "analyzedPages": "all",
    "totalEntries": 0,
    "entriesWithPages": 0,
    "overallConfidence": 90,
    "warnings": []
  }
}

Begin analysis now. Return ONLY the JSON.`;
}

// ============================================
// DynamoDB Storage
// ============================================

/**
 * Store TOC structure in DynamoDB
 */
async function storeTocInDynamoDB(
  bookId: string,
  toc: AutoGeneratedTOC
): Promise<TocExtractionResult> {
  logger.info('Storing TOC structure in DynamoDB', { bookId });

  const chapters: TocExtractionResult['chapters'] = [];
  const topics: TocExtractionResult['topics'] = [];
  const subtopics: TocExtractionResult['subtopics'] = [];

  // Store chapters
  for (const chapter of toc.chapters) {
    const chapterId = uuidv4();
    chapters.push({
      chapterId,
      title: chapter.title,
      bookId,
      order: chapter.chapterNumber - 1,
      pageStart: chapter.startPage,
      pageEnd: chapter.endPage,
    });

    await docClient.send(new PutCommand({
      TableName: CHAPTERS_TABLE,
      Item: {
        chapterId,
        bookId,
        title: chapter.title,
        order: chapter.chapterNumber - 1,
        pageStart: chapter.startPage,
        pageEnd: chapter.endPage,
        confidence: chapter.confidence,
        createdAt: new Date().toISOString(),
      }
    }));

    // Store in local map for topic lookup
    chapterIdMap.set(chapter.chapterNumber, chapterId);
  }

  // Store topics
  for (const topic of toc.topics) {
    const parentChapter = chapters.find(c => c.order + 1 === topic.parentChapterNumber);
    if (!parentChapter) {
      logger.warn(`Topic ${topic.topicNumber} has no parent chapter ${topic.parentChapterNumber}`);
      continue;
    }

    const topicId = uuidv4();
    topics.push({
      topicId,
      title: topic.title,
      chapterId: parentChapter.chapterId,
      order: parseInt(topic.topicNumber.split('.')[1] || '0', 10),
      pageStart: topic.startPage,
      pageEnd: topic.endPage,
    });

    await docClient.send(new PutCommand({
      TableName: TOPICS_TABLE,
      Item: {
        topicId,
        chapterId: parentChapter.chapterId,
        title: topic.title,
        order: parseInt(topic.topicNumber.split('.')[1] || '0', 10),
        pageStart: topic.startPage,
        pageEnd: topic.endPage,
        confidence: topic.confidence,
        createdAt: new Date().toISOString(),
      }
    }));
  }

  // Store subtopics
  for (const subTopic of toc.subTopics) {
    const parentTopic = topics.find(t => t.order === parseInt(subTopic.parentTopicNumber.split('.')[1] || '0', 10));
    if (!parentTopic) {
      logger.warn(`SubTopic ${subTopic.subTopicNumber} has no parent topic ${subTopic.parentTopicNumber}`);
      continue;
    }

    const subtopicId = uuidv4();
    subtopics.push({
      subtopicId,
      title: subTopic.title,
      topicId: parentTopic.topicId,
      order: parseInt(subTopic.subTopicNumber.split('.').slice(2).join('.') || '0', 10),
      pageStart: subTopic.startPage,
      pageEnd: subTopic.endPage,
    });

    await docClient.send(new PutCommand({
      TableName: SUBTOPICS_TABLE,
      Item: {
        subtopicId,
        topicId: parentTopic.topicId,
        title: subTopic.title,
        order: parseInt(subTopic.subTopicNumber.split('.').slice(2).join('.') || '0', 10),
        pageStart: subTopic.startPage,
        pageEnd: subTopic.endPage,
        confidence: subTopic.confidence,
        createdAt: new Date().toISOString(),
      }
    }));
  }

  // Update book with TOC metadata
  await docClient.send(new PutCommand({
    TableName: BOOKS_TABLE,
    Key: { bookId },
    UpdateExpression: 'SET #tocGenerated = :tocGenerated, #tocConfidence = :confidence, #tocGeneratedAt = :now',
    ExpressionAttributeNames: { '#tocGenerated': 'tocGenerated', '#tocConfidence': 'tocConfidence', '#tocGeneratedAt': 'tocGeneratedAt' },
    ExpressionAttributeValues: {
      ':tocGenerated': true,
      ':confidence': toc.metadata.overallConfidence,
      ':now': new Date().toISOString(),
    },
  }));

  logger.info('TOC structure stored successfully');
  return { chapters, topics, subtopics };
}

export default { extractToc };